// source: proto/v1beta1/source.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.grafeas.v1beta1.source.AliasContext', null, global);
goog.exportSymbol('proto.grafeas.v1beta1.source.AliasContext.Kind', null, global);
goog.exportSymbol('proto.grafeas.v1beta1.source.CloudRepoSourceContext', null, global);
goog.exportSymbol('proto.grafeas.v1beta1.source.CloudRepoSourceContext.RevisionCase', null, global);
goog.exportSymbol('proto.grafeas.v1beta1.source.GerritSourceContext', null, global);
goog.exportSymbol('proto.grafeas.v1beta1.source.GerritSourceContext.RevisionCase', null, global);
goog.exportSymbol('proto.grafeas.v1beta1.source.GitSourceContext', null, global);
goog.exportSymbol('proto.grafeas.v1beta1.source.ProjectRepoId', null, global);
goog.exportSymbol('proto.grafeas.v1beta1.source.RepoId', null, global);
goog.exportSymbol('proto.grafeas.v1beta1.source.RepoId.IdCase', null, global);
goog.exportSymbol('proto.grafeas.v1beta1.source.SourceContext', null, global);
goog.exportSymbol('proto.grafeas.v1beta1.source.SourceContext.ContextCase', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.grafeas.v1beta1.source.SourceContext = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.grafeas.v1beta1.source.SourceContext.oneofGroups_);
};
goog.inherits(proto.grafeas.v1beta1.source.SourceContext, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.grafeas.v1beta1.source.SourceContext.displayName = 'proto.grafeas.v1beta1.source.SourceContext';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.grafeas.v1beta1.source.AliasContext = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.grafeas.v1beta1.source.AliasContext, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.grafeas.v1beta1.source.AliasContext.displayName = 'proto.grafeas.v1beta1.source.AliasContext';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.grafeas.v1beta1.source.CloudRepoSourceContext = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.grafeas.v1beta1.source.CloudRepoSourceContext.oneofGroups_);
};
goog.inherits(proto.grafeas.v1beta1.source.CloudRepoSourceContext, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.grafeas.v1beta1.source.CloudRepoSourceContext.displayName = 'proto.grafeas.v1beta1.source.CloudRepoSourceContext';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.grafeas.v1beta1.source.GerritSourceContext = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.grafeas.v1beta1.source.GerritSourceContext.oneofGroups_);
};
goog.inherits(proto.grafeas.v1beta1.source.GerritSourceContext, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.grafeas.v1beta1.source.GerritSourceContext.displayName = 'proto.grafeas.v1beta1.source.GerritSourceContext';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.grafeas.v1beta1.source.GitSourceContext = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.grafeas.v1beta1.source.GitSourceContext, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.grafeas.v1beta1.source.GitSourceContext.displayName = 'proto.grafeas.v1beta1.source.GitSourceContext';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.grafeas.v1beta1.source.RepoId = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.grafeas.v1beta1.source.RepoId.oneofGroups_);
};
goog.inherits(proto.grafeas.v1beta1.source.RepoId, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.grafeas.v1beta1.source.RepoId.displayName = 'proto.grafeas.v1beta1.source.RepoId';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.grafeas.v1beta1.source.ProjectRepoId = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.grafeas.v1beta1.source.ProjectRepoId, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.grafeas.v1beta1.source.ProjectRepoId.displayName = 'proto.grafeas.v1beta1.source.ProjectRepoId';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.grafeas.v1beta1.source.SourceContext.oneofGroups_ = [[1,2,3]];

/**
 * @enum {number}
 */
proto.grafeas.v1beta1.source.SourceContext.ContextCase = {
  CONTEXT_NOT_SET: 0,
  CLOUD_REPO: 1,
  GERRIT: 2,
  GIT: 3
};

/**
 * @return {proto.grafeas.v1beta1.source.SourceContext.ContextCase}
 */
proto.grafeas.v1beta1.source.SourceContext.prototype.getContextCase = function() {
  return /** @type {proto.grafeas.v1beta1.source.SourceContext.ContextCase} */(jspb.Message.computeOneofCase(this, proto.grafeas.v1beta1.source.SourceContext.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.grafeas.v1beta1.source.SourceContext.prototype.toObject = function(opt_includeInstance) {
  return proto.grafeas.v1beta1.source.SourceContext.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.grafeas.v1beta1.source.SourceContext} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.grafeas.v1beta1.source.SourceContext.toObject = function(includeInstance, msg) {
  var f, obj = {
    cloudRepo: (f = msg.getCloudRepo()) && proto.grafeas.v1beta1.source.CloudRepoSourceContext.toObject(includeInstance, f),
    gerrit: (f = msg.getGerrit()) && proto.grafeas.v1beta1.source.GerritSourceContext.toObject(includeInstance, f),
    git: (f = msg.getGit()) && proto.grafeas.v1beta1.source.GitSourceContext.toObject(includeInstance, f),
    labelsMap: (f = msg.getLabelsMap()) ? f.toObject(includeInstance, undefined) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.grafeas.v1beta1.source.SourceContext}
 */
proto.grafeas.v1beta1.source.SourceContext.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.grafeas.v1beta1.source.SourceContext;
  return proto.grafeas.v1beta1.source.SourceContext.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.grafeas.v1beta1.source.SourceContext} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.grafeas.v1beta1.source.SourceContext}
 */
proto.grafeas.v1beta1.source.SourceContext.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.grafeas.v1beta1.source.CloudRepoSourceContext;
      reader.readMessage(value,proto.grafeas.v1beta1.source.CloudRepoSourceContext.deserializeBinaryFromReader);
      msg.setCloudRepo(value);
      break;
    case 2:
      var value = new proto.grafeas.v1beta1.source.GerritSourceContext;
      reader.readMessage(value,proto.grafeas.v1beta1.source.GerritSourceContext.deserializeBinaryFromReader);
      msg.setGerrit(value);
      break;
    case 3:
      var value = new proto.grafeas.v1beta1.source.GitSourceContext;
      reader.readMessage(value,proto.grafeas.v1beta1.source.GitSourceContext.deserializeBinaryFromReader);
      msg.setGit(value);
      break;
    case 4:
      var value = msg.getLabelsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.grafeas.v1beta1.source.SourceContext.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.grafeas.v1beta1.source.SourceContext.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.grafeas.v1beta1.source.SourceContext} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.grafeas.v1beta1.source.SourceContext.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCloudRepo();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.grafeas.v1beta1.source.CloudRepoSourceContext.serializeBinaryToWriter
    );
  }
  f = message.getGerrit();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.grafeas.v1beta1.source.GerritSourceContext.serializeBinaryToWriter
    );
  }
  f = message.getGit();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.grafeas.v1beta1.source.GitSourceContext.serializeBinaryToWriter
    );
  }
  f = message.getLabelsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(4, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
};


/**
 * optional CloudRepoSourceContext cloud_repo = 1;
 * @return {?proto.grafeas.v1beta1.source.CloudRepoSourceContext}
 */
proto.grafeas.v1beta1.source.SourceContext.prototype.getCloudRepo = function() {
  return /** @type{?proto.grafeas.v1beta1.source.CloudRepoSourceContext} */ (
    jspb.Message.getWrapperField(this, proto.grafeas.v1beta1.source.CloudRepoSourceContext, 1));
};


/**
 * @param {?proto.grafeas.v1beta1.source.CloudRepoSourceContext|undefined} value
 * @return {!proto.grafeas.v1beta1.source.SourceContext} returns this
*/
proto.grafeas.v1beta1.source.SourceContext.prototype.setCloudRepo = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.grafeas.v1beta1.source.SourceContext.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.grafeas.v1beta1.source.SourceContext} returns this
 */
proto.grafeas.v1beta1.source.SourceContext.prototype.clearCloudRepo = function() {
  return this.setCloudRepo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.grafeas.v1beta1.source.SourceContext.prototype.hasCloudRepo = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional GerritSourceContext gerrit = 2;
 * @return {?proto.grafeas.v1beta1.source.GerritSourceContext}
 */
proto.grafeas.v1beta1.source.SourceContext.prototype.getGerrit = function() {
  return /** @type{?proto.grafeas.v1beta1.source.GerritSourceContext} */ (
    jspb.Message.getWrapperField(this, proto.grafeas.v1beta1.source.GerritSourceContext, 2));
};


/**
 * @param {?proto.grafeas.v1beta1.source.GerritSourceContext|undefined} value
 * @return {!proto.grafeas.v1beta1.source.SourceContext} returns this
*/
proto.grafeas.v1beta1.source.SourceContext.prototype.setGerrit = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.grafeas.v1beta1.source.SourceContext.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.grafeas.v1beta1.source.SourceContext} returns this
 */
proto.grafeas.v1beta1.source.SourceContext.prototype.clearGerrit = function() {
  return this.setGerrit(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.grafeas.v1beta1.source.SourceContext.prototype.hasGerrit = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional GitSourceContext git = 3;
 * @return {?proto.grafeas.v1beta1.source.GitSourceContext}
 */
proto.grafeas.v1beta1.source.SourceContext.prototype.getGit = function() {
  return /** @type{?proto.grafeas.v1beta1.source.GitSourceContext} */ (
    jspb.Message.getWrapperField(this, proto.grafeas.v1beta1.source.GitSourceContext, 3));
};


/**
 * @param {?proto.grafeas.v1beta1.source.GitSourceContext|undefined} value
 * @return {!proto.grafeas.v1beta1.source.SourceContext} returns this
*/
proto.grafeas.v1beta1.source.SourceContext.prototype.setGit = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.grafeas.v1beta1.source.SourceContext.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.grafeas.v1beta1.source.SourceContext} returns this
 */
proto.grafeas.v1beta1.source.SourceContext.prototype.clearGit = function() {
  return this.setGit(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.grafeas.v1beta1.source.SourceContext.prototype.hasGit = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * map<string, string> labels = 4;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.grafeas.v1beta1.source.SourceContext.prototype.getLabelsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 4, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.grafeas.v1beta1.source.SourceContext} returns this
 */
proto.grafeas.v1beta1.source.SourceContext.prototype.clearLabelsMap = function() {
  this.getLabelsMap().clear();
  return this;};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.grafeas.v1beta1.source.AliasContext.prototype.toObject = function(opt_includeInstance) {
  return proto.grafeas.v1beta1.source.AliasContext.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.grafeas.v1beta1.source.AliasContext} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.grafeas.v1beta1.source.AliasContext.toObject = function(includeInstance, msg) {
  var f, obj = {
    kind: jspb.Message.getFieldWithDefault(msg, 1, 0),
    name: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.grafeas.v1beta1.source.AliasContext}
 */
proto.grafeas.v1beta1.source.AliasContext.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.grafeas.v1beta1.source.AliasContext;
  return proto.grafeas.v1beta1.source.AliasContext.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.grafeas.v1beta1.source.AliasContext} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.grafeas.v1beta1.source.AliasContext}
 */
proto.grafeas.v1beta1.source.AliasContext.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.grafeas.v1beta1.source.AliasContext.Kind} */ (reader.readEnum());
      msg.setKind(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.grafeas.v1beta1.source.AliasContext.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.grafeas.v1beta1.source.AliasContext.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.grafeas.v1beta1.source.AliasContext} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.grafeas.v1beta1.source.AliasContext.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getKind();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.grafeas.v1beta1.source.AliasContext.Kind = {
  KIND_UNSPECIFIED: 0,
  FIXED: 1,
  MOVABLE: 2,
  OTHER: 4
};

/**
 * optional Kind kind = 1;
 * @return {!proto.grafeas.v1beta1.source.AliasContext.Kind}
 */
proto.grafeas.v1beta1.source.AliasContext.prototype.getKind = function() {
  return /** @type {!proto.grafeas.v1beta1.source.AliasContext.Kind} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.grafeas.v1beta1.source.AliasContext.Kind} value
 * @return {!proto.grafeas.v1beta1.source.AliasContext} returns this
 */
proto.grafeas.v1beta1.source.AliasContext.prototype.setKind = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.grafeas.v1beta1.source.AliasContext.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.grafeas.v1beta1.source.AliasContext} returns this
 */
proto.grafeas.v1beta1.source.AliasContext.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.grafeas.v1beta1.source.CloudRepoSourceContext.oneofGroups_ = [[2,3]];

/**
 * @enum {number}
 */
proto.grafeas.v1beta1.source.CloudRepoSourceContext.RevisionCase = {
  REVISION_NOT_SET: 0,
  REVISION_ID: 2,
  ALIAS_CONTEXT: 3
};

/**
 * @return {proto.grafeas.v1beta1.source.CloudRepoSourceContext.RevisionCase}
 */
proto.grafeas.v1beta1.source.CloudRepoSourceContext.prototype.getRevisionCase = function() {
  return /** @type {proto.grafeas.v1beta1.source.CloudRepoSourceContext.RevisionCase} */(jspb.Message.computeOneofCase(this, proto.grafeas.v1beta1.source.CloudRepoSourceContext.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.grafeas.v1beta1.source.CloudRepoSourceContext.prototype.toObject = function(opt_includeInstance) {
  return proto.grafeas.v1beta1.source.CloudRepoSourceContext.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.grafeas.v1beta1.source.CloudRepoSourceContext} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.grafeas.v1beta1.source.CloudRepoSourceContext.toObject = function(includeInstance, msg) {
  var f, obj = {
    repoId: (f = msg.getRepoId()) && proto.grafeas.v1beta1.source.RepoId.toObject(includeInstance, f),
    revisionId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    aliasContext: (f = msg.getAliasContext()) && proto.grafeas.v1beta1.source.AliasContext.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.grafeas.v1beta1.source.CloudRepoSourceContext}
 */
proto.grafeas.v1beta1.source.CloudRepoSourceContext.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.grafeas.v1beta1.source.CloudRepoSourceContext;
  return proto.grafeas.v1beta1.source.CloudRepoSourceContext.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.grafeas.v1beta1.source.CloudRepoSourceContext} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.grafeas.v1beta1.source.CloudRepoSourceContext}
 */
proto.grafeas.v1beta1.source.CloudRepoSourceContext.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.grafeas.v1beta1.source.RepoId;
      reader.readMessage(value,proto.grafeas.v1beta1.source.RepoId.deserializeBinaryFromReader);
      msg.setRepoId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setRevisionId(value);
      break;
    case 3:
      var value = new proto.grafeas.v1beta1.source.AliasContext;
      reader.readMessage(value,proto.grafeas.v1beta1.source.AliasContext.deserializeBinaryFromReader);
      msg.setAliasContext(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.grafeas.v1beta1.source.CloudRepoSourceContext.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.grafeas.v1beta1.source.CloudRepoSourceContext.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.grafeas.v1beta1.source.CloudRepoSourceContext} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.grafeas.v1beta1.source.CloudRepoSourceContext.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRepoId();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.grafeas.v1beta1.source.RepoId.serializeBinaryToWriter
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getAliasContext();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.grafeas.v1beta1.source.AliasContext.serializeBinaryToWriter
    );
  }
};


/**
 * optional RepoId repo_id = 1;
 * @return {?proto.grafeas.v1beta1.source.RepoId}
 */
proto.grafeas.v1beta1.source.CloudRepoSourceContext.prototype.getRepoId = function() {
  return /** @type{?proto.grafeas.v1beta1.source.RepoId} */ (
    jspb.Message.getWrapperField(this, proto.grafeas.v1beta1.source.RepoId, 1));
};


/**
 * @param {?proto.grafeas.v1beta1.source.RepoId|undefined} value
 * @return {!proto.grafeas.v1beta1.source.CloudRepoSourceContext} returns this
*/
proto.grafeas.v1beta1.source.CloudRepoSourceContext.prototype.setRepoId = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.grafeas.v1beta1.source.CloudRepoSourceContext} returns this
 */
proto.grafeas.v1beta1.source.CloudRepoSourceContext.prototype.clearRepoId = function() {
  return this.setRepoId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.grafeas.v1beta1.source.CloudRepoSourceContext.prototype.hasRepoId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string revision_id = 2;
 * @return {string}
 */
proto.grafeas.v1beta1.source.CloudRepoSourceContext.prototype.getRevisionId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.grafeas.v1beta1.source.CloudRepoSourceContext} returns this
 */
proto.grafeas.v1beta1.source.CloudRepoSourceContext.prototype.setRevisionId = function(value) {
  return jspb.Message.setOneofField(this, 2, proto.grafeas.v1beta1.source.CloudRepoSourceContext.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.grafeas.v1beta1.source.CloudRepoSourceContext} returns this
 */
proto.grafeas.v1beta1.source.CloudRepoSourceContext.prototype.clearRevisionId = function() {
  return jspb.Message.setOneofField(this, 2, proto.grafeas.v1beta1.source.CloudRepoSourceContext.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.grafeas.v1beta1.source.CloudRepoSourceContext.prototype.hasRevisionId = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional AliasContext alias_context = 3;
 * @return {?proto.grafeas.v1beta1.source.AliasContext}
 */
proto.grafeas.v1beta1.source.CloudRepoSourceContext.prototype.getAliasContext = function() {
  return /** @type{?proto.grafeas.v1beta1.source.AliasContext} */ (
    jspb.Message.getWrapperField(this, proto.grafeas.v1beta1.source.AliasContext, 3));
};


/**
 * @param {?proto.grafeas.v1beta1.source.AliasContext|undefined} value
 * @return {!proto.grafeas.v1beta1.source.CloudRepoSourceContext} returns this
*/
proto.grafeas.v1beta1.source.CloudRepoSourceContext.prototype.setAliasContext = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.grafeas.v1beta1.source.CloudRepoSourceContext.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.grafeas.v1beta1.source.CloudRepoSourceContext} returns this
 */
proto.grafeas.v1beta1.source.CloudRepoSourceContext.prototype.clearAliasContext = function() {
  return this.setAliasContext(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.grafeas.v1beta1.source.CloudRepoSourceContext.prototype.hasAliasContext = function() {
  return jspb.Message.getField(this, 3) != null;
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.grafeas.v1beta1.source.GerritSourceContext.oneofGroups_ = [[3,4]];

/**
 * @enum {number}
 */
proto.grafeas.v1beta1.source.GerritSourceContext.RevisionCase = {
  REVISION_NOT_SET: 0,
  REVISION_ID: 3,
  ALIAS_CONTEXT: 4
};

/**
 * @return {proto.grafeas.v1beta1.source.GerritSourceContext.RevisionCase}
 */
proto.grafeas.v1beta1.source.GerritSourceContext.prototype.getRevisionCase = function() {
  return /** @type {proto.grafeas.v1beta1.source.GerritSourceContext.RevisionCase} */(jspb.Message.computeOneofCase(this, proto.grafeas.v1beta1.source.GerritSourceContext.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.grafeas.v1beta1.source.GerritSourceContext.prototype.toObject = function(opt_includeInstance) {
  return proto.grafeas.v1beta1.source.GerritSourceContext.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.grafeas.v1beta1.source.GerritSourceContext} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.grafeas.v1beta1.source.GerritSourceContext.toObject = function(includeInstance, msg) {
  var f, obj = {
    hostUri: jspb.Message.getFieldWithDefault(msg, 1, ""),
    gerritProject: jspb.Message.getFieldWithDefault(msg, 2, ""),
    revisionId: jspb.Message.getFieldWithDefault(msg, 3, ""),
    aliasContext: (f = msg.getAliasContext()) && proto.grafeas.v1beta1.source.AliasContext.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.grafeas.v1beta1.source.GerritSourceContext}
 */
proto.grafeas.v1beta1.source.GerritSourceContext.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.grafeas.v1beta1.source.GerritSourceContext;
  return proto.grafeas.v1beta1.source.GerritSourceContext.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.grafeas.v1beta1.source.GerritSourceContext} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.grafeas.v1beta1.source.GerritSourceContext}
 */
proto.grafeas.v1beta1.source.GerritSourceContext.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setHostUri(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setGerritProject(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setRevisionId(value);
      break;
    case 4:
      var value = new proto.grafeas.v1beta1.source.AliasContext;
      reader.readMessage(value,proto.grafeas.v1beta1.source.AliasContext.deserializeBinaryFromReader);
      msg.setAliasContext(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.grafeas.v1beta1.source.GerritSourceContext.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.grafeas.v1beta1.source.GerritSourceContext.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.grafeas.v1beta1.source.GerritSourceContext} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.grafeas.v1beta1.source.GerritSourceContext.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHostUri();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getGerritProject();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getAliasContext();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.grafeas.v1beta1.source.AliasContext.serializeBinaryToWriter
    );
  }
};


/**
 * optional string host_uri = 1;
 * @return {string}
 */
proto.grafeas.v1beta1.source.GerritSourceContext.prototype.getHostUri = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.grafeas.v1beta1.source.GerritSourceContext} returns this
 */
proto.grafeas.v1beta1.source.GerritSourceContext.prototype.setHostUri = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string gerrit_project = 2;
 * @return {string}
 */
proto.grafeas.v1beta1.source.GerritSourceContext.prototype.getGerritProject = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.grafeas.v1beta1.source.GerritSourceContext} returns this
 */
proto.grafeas.v1beta1.source.GerritSourceContext.prototype.setGerritProject = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string revision_id = 3;
 * @return {string}
 */
proto.grafeas.v1beta1.source.GerritSourceContext.prototype.getRevisionId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.grafeas.v1beta1.source.GerritSourceContext} returns this
 */
proto.grafeas.v1beta1.source.GerritSourceContext.prototype.setRevisionId = function(value) {
  return jspb.Message.setOneofField(this, 3, proto.grafeas.v1beta1.source.GerritSourceContext.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.grafeas.v1beta1.source.GerritSourceContext} returns this
 */
proto.grafeas.v1beta1.source.GerritSourceContext.prototype.clearRevisionId = function() {
  return jspb.Message.setOneofField(this, 3, proto.grafeas.v1beta1.source.GerritSourceContext.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.grafeas.v1beta1.source.GerritSourceContext.prototype.hasRevisionId = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional AliasContext alias_context = 4;
 * @return {?proto.grafeas.v1beta1.source.AliasContext}
 */
proto.grafeas.v1beta1.source.GerritSourceContext.prototype.getAliasContext = function() {
  return /** @type{?proto.grafeas.v1beta1.source.AliasContext} */ (
    jspb.Message.getWrapperField(this, proto.grafeas.v1beta1.source.AliasContext, 4));
};


/**
 * @param {?proto.grafeas.v1beta1.source.AliasContext|undefined} value
 * @return {!proto.grafeas.v1beta1.source.GerritSourceContext} returns this
*/
proto.grafeas.v1beta1.source.GerritSourceContext.prototype.setAliasContext = function(value) {
  return jspb.Message.setOneofWrapperField(this, 4, proto.grafeas.v1beta1.source.GerritSourceContext.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.grafeas.v1beta1.source.GerritSourceContext} returns this
 */
proto.grafeas.v1beta1.source.GerritSourceContext.prototype.clearAliasContext = function() {
  return this.setAliasContext(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.grafeas.v1beta1.source.GerritSourceContext.prototype.hasAliasContext = function() {
  return jspb.Message.getField(this, 4) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.grafeas.v1beta1.source.GitSourceContext.prototype.toObject = function(opt_includeInstance) {
  return proto.grafeas.v1beta1.source.GitSourceContext.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.grafeas.v1beta1.source.GitSourceContext} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.grafeas.v1beta1.source.GitSourceContext.toObject = function(includeInstance, msg) {
  var f, obj = {
    url: jspb.Message.getFieldWithDefault(msg, 1, ""),
    revisionId: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.grafeas.v1beta1.source.GitSourceContext}
 */
proto.grafeas.v1beta1.source.GitSourceContext.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.grafeas.v1beta1.source.GitSourceContext;
  return proto.grafeas.v1beta1.source.GitSourceContext.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.grafeas.v1beta1.source.GitSourceContext} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.grafeas.v1beta1.source.GitSourceContext}
 */
proto.grafeas.v1beta1.source.GitSourceContext.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUrl(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setRevisionId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.grafeas.v1beta1.source.GitSourceContext.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.grafeas.v1beta1.source.GitSourceContext.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.grafeas.v1beta1.source.GitSourceContext} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.grafeas.v1beta1.source.GitSourceContext.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUrl();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getRevisionId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string url = 1;
 * @return {string}
 */
proto.grafeas.v1beta1.source.GitSourceContext.prototype.getUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.grafeas.v1beta1.source.GitSourceContext} returns this
 */
proto.grafeas.v1beta1.source.GitSourceContext.prototype.setUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string revision_id = 2;
 * @return {string}
 */
proto.grafeas.v1beta1.source.GitSourceContext.prototype.getRevisionId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.grafeas.v1beta1.source.GitSourceContext} returns this
 */
proto.grafeas.v1beta1.source.GitSourceContext.prototype.setRevisionId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.grafeas.v1beta1.source.RepoId.oneofGroups_ = [[1,2]];

/**
 * @enum {number}
 */
proto.grafeas.v1beta1.source.RepoId.IdCase = {
  ID_NOT_SET: 0,
  PROJECT_REPO_ID: 1,
  UID: 2
};

/**
 * @return {proto.grafeas.v1beta1.source.RepoId.IdCase}
 */
proto.grafeas.v1beta1.source.RepoId.prototype.getIdCase = function() {
  return /** @type {proto.grafeas.v1beta1.source.RepoId.IdCase} */(jspb.Message.computeOneofCase(this, proto.grafeas.v1beta1.source.RepoId.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.grafeas.v1beta1.source.RepoId.prototype.toObject = function(opt_includeInstance) {
  return proto.grafeas.v1beta1.source.RepoId.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.grafeas.v1beta1.source.RepoId} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.grafeas.v1beta1.source.RepoId.toObject = function(includeInstance, msg) {
  var f, obj = {
    projectRepoId: (f = msg.getProjectRepoId()) && proto.grafeas.v1beta1.source.ProjectRepoId.toObject(includeInstance, f),
    uid: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.grafeas.v1beta1.source.RepoId}
 */
proto.grafeas.v1beta1.source.RepoId.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.grafeas.v1beta1.source.RepoId;
  return proto.grafeas.v1beta1.source.RepoId.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.grafeas.v1beta1.source.RepoId} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.grafeas.v1beta1.source.RepoId}
 */
proto.grafeas.v1beta1.source.RepoId.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.grafeas.v1beta1.source.ProjectRepoId;
      reader.readMessage(value,proto.grafeas.v1beta1.source.ProjectRepoId.deserializeBinaryFromReader);
      msg.setProjectRepoId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setUid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.grafeas.v1beta1.source.RepoId.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.grafeas.v1beta1.source.RepoId.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.grafeas.v1beta1.source.RepoId} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.grafeas.v1beta1.source.RepoId.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProjectRepoId();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.grafeas.v1beta1.source.ProjectRepoId.serializeBinaryToWriter
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional ProjectRepoId project_repo_id = 1;
 * @return {?proto.grafeas.v1beta1.source.ProjectRepoId}
 */
proto.grafeas.v1beta1.source.RepoId.prototype.getProjectRepoId = function() {
  return /** @type{?proto.grafeas.v1beta1.source.ProjectRepoId} */ (
    jspb.Message.getWrapperField(this, proto.grafeas.v1beta1.source.ProjectRepoId, 1));
};


/**
 * @param {?proto.grafeas.v1beta1.source.ProjectRepoId|undefined} value
 * @return {!proto.grafeas.v1beta1.source.RepoId} returns this
*/
proto.grafeas.v1beta1.source.RepoId.prototype.setProjectRepoId = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.grafeas.v1beta1.source.RepoId.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.grafeas.v1beta1.source.RepoId} returns this
 */
proto.grafeas.v1beta1.source.RepoId.prototype.clearProjectRepoId = function() {
  return this.setProjectRepoId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.grafeas.v1beta1.source.RepoId.prototype.hasProjectRepoId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string uid = 2;
 * @return {string}
 */
proto.grafeas.v1beta1.source.RepoId.prototype.getUid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.grafeas.v1beta1.source.RepoId} returns this
 */
proto.grafeas.v1beta1.source.RepoId.prototype.setUid = function(value) {
  return jspb.Message.setOneofField(this, 2, proto.grafeas.v1beta1.source.RepoId.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.grafeas.v1beta1.source.RepoId} returns this
 */
proto.grafeas.v1beta1.source.RepoId.prototype.clearUid = function() {
  return jspb.Message.setOneofField(this, 2, proto.grafeas.v1beta1.source.RepoId.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.grafeas.v1beta1.source.RepoId.prototype.hasUid = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.grafeas.v1beta1.source.ProjectRepoId.prototype.toObject = function(opt_includeInstance) {
  return proto.grafeas.v1beta1.source.ProjectRepoId.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.grafeas.v1beta1.source.ProjectRepoId} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.grafeas.v1beta1.source.ProjectRepoId.toObject = function(includeInstance, msg) {
  var f, obj = {
    projectId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    repoName: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.grafeas.v1beta1.source.ProjectRepoId}
 */
proto.grafeas.v1beta1.source.ProjectRepoId.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.grafeas.v1beta1.source.ProjectRepoId;
  return proto.grafeas.v1beta1.source.ProjectRepoId.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.grafeas.v1beta1.source.ProjectRepoId} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.grafeas.v1beta1.source.ProjectRepoId}
 */
proto.grafeas.v1beta1.source.ProjectRepoId.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setProjectId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setRepoName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.grafeas.v1beta1.source.ProjectRepoId.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.grafeas.v1beta1.source.ProjectRepoId.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.grafeas.v1beta1.source.ProjectRepoId} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.grafeas.v1beta1.source.ProjectRepoId.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProjectId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getRepoName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string project_id = 1;
 * @return {string}
 */
proto.grafeas.v1beta1.source.ProjectRepoId.prototype.getProjectId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.grafeas.v1beta1.source.ProjectRepoId} returns this
 */
proto.grafeas.v1beta1.source.ProjectRepoId.prototype.setProjectId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string repo_name = 2;
 * @return {string}
 */
proto.grafeas.v1beta1.source.ProjectRepoId.prototype.getRepoName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.grafeas.v1beta1.source.ProjectRepoId} returns this
 */
proto.grafeas.v1beta1.source.ProjectRepoId.prototype.setRepoName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


goog.object.extend(exports, proto.grafeas.v1beta1.source);
