name: Publish

on:
  push:
    tags:
      - v*.*.*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV
      - uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: |
          yarn
          yarn verify
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_USER }}
          password: ${{ secrets.CR_PAT }}

      - id: gitextra
        uses: liatrio/github-actions/git-extra@master

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/rode/ui:latest
            ghcr.io/rode/ui:${{ steps.gitextra.outputs.version }}

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v1.7.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          configuration: release.json

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            ${{steps.github_release.outputs.changelog}}
            ## Docker images
            - `ghcr.io/rode/ui:latest`
            - `ghcr.io/rode/ui:${{ steps.gitextra.outputs.version }}`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  chart-promote:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
          repository: rode/charts
      - name: Get tag
        id: tag
        run: echo ::set-output name=TAG::${GITHUB_REF#refs/tags/v}
      - name: Increment chart version
        uses: liatrio/github-actions/gitops-semver-increment-yaml@master
        with:
          file: charts/rode-ui/Chart.yaml
          path: .version
          position: PATCH
      - name: Update application version
        uses: liatrio/github-actions/gitops-update-yaml@master
        with:
          file: charts/rode-ui/Chart.yaml
          path: .appVersion
          value: ${{ steps.tag.outputs.TAG }}
      - name: Create pull request
        uses: liatrio/github-actions/gitops-gh-pr@master
        with:
          repo: rode/charts
          token: ${{ secrets.GITOPS_TOKEN }}
          message: "update Rode app version to ${{ steps.tag.outputs.TAG }}"
