name: Verify

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV
      - uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: |
          yarn
          yarn verify
  license-check:
    runs-on: ubuntu-latest
    container: golang:1.15
    steps:
      - uses: actions/checkout@v2
      - name: Download License Utility
        run: go get -u github.com/google/addlicense
      - name: Check License Headers
        run: |
          shopt -s globstar
          addlicense -check **/*.{js,scss}
        shell: bash
