name: Verify

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV
      - uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Test
        run: |
          yarn
          yarn verify
      - name: Build Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
  license-check:
    runs-on: ubuntu-latest
    container: golang:1.16
    steps:
      - uses: actions/checkout@v2
      - name: Download License Utility
        run: go install github.com/google/addlicense@master
      - name: Check License Headers
        run: |
          shopt -s globstar
          addlicense -check **/*.{js,scss}
        shell: bash
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          start: yarn dev
          wait-on: "http://localhost:3000"
